version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./uploads:/app/uploads
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: "1"
      DATABASE_PATH: /app/vulneats.db
      UPLOAD_FOLDER: /app/uploads
      DATABASE_URL: "postgresql://neondb_owner:npg_75xImXtNePLH@ep-holy-haze-a1c2ms4i-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      CLOUDINARY_CLOUD_NAME: dpkakpm7v
      CLOUDINARY_API_KEY: "623281826869567"
      CLOUDINARY_API_SECRET: "U_VxEoVJQ97t40qVMNkia86H8ks"
    restart: unless-stopped
    command: python backend/app.py

  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:5001
      - INTERNAL_API_BASE=http://backend:5001
    depends_on:
      - backend
