version: '3.8'

services:
  vulneats:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./vulneats.db:/app/vulneats.db
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped
    command: python app.py
